---
- name: "Launch requested job of type {{ deployer_action }} of {{ scm_reference }}"
  tower_job_launch:
    job_template:     "{{ deployer_action }}-{{ deployer_type }}-{{ scm_reference | default(scm_branch) }}"
    inventory:        "empty-inventory-{{ babylon_region | default (anarchy_region) | default('dev') }}"
    extra_vars:       "@{{ babylon_manifest_directory }}/{{ deployer_type }}-{{ deployer_action }}-{{ scm_reference }}-{{ guid }}.yml"
  register: r_tower_job_launch

    #extra_vars:           "@{{ extra_var_file_directory }}/{{ deployer_type }}-{{ scm_reference }}-{{ guid }}.yml"

- name: Callback - Job Launch status
  debug:
    msg: Placeholder, callback goes here

- name: Wait for job to complete
  tower_job_wait:
    job_id:   "{{ r_tower_job_launch.id }}"
    timeout:  "{{ tower_job_timeout | default(1800) }}"
  register: r_tower_job_status

- name: Callback - Job Status
  debug:
    msg: Placeholder, callback goes here
...
