---
- name: "Launch requested Job of type {{ job_vars['__meta__']['tower']['action'] }} of {{ job_vars['__meta__']['deployer']['scm_ref'] }}"
  tower_job_launch:
    job_template: >-
                                  {{
                                    job_vars['__meta__']['tower']['action'] ~ '-'
                                    ~ job_vars['__meta__']['deployer']['type'] ~ '-'
                                    ~ job_vars['__meta__']['deployer']['scm_ref']
                                  }}
    inventory:        "empty-inventory-{{ job_vars['__meta__']['tower']['run_group'] | default('default') }}"
    extra_vars: >-
                                {{ 
                                  '@' ~ babylon_manifest_directory ~ '/'
                                   ~ job_vars['__meta__']['deployer']['type'] ~ '-'
                                   ~ job_vars['__meta__']['tower']['action'] ~ '-'
                                   ~ job_vars['__meta__']['deployer']['scm_ref'] ~ '-'
                                   ~ job_vars['guid'] ~ '.yml'
                                 }}
  register:       r_tower_job_launch

- name: Callback to Anarchy with Job LAUNCH Status
  include_role:
    name: anarchy-job-status-callback
    allow_duplicates: yes
  vars:
    babylon_callback_event: started
    babylon_message:
      - "{{ job_vars['__meta__']['tower']['action'] }}-{{ job_vars['__meta__']['deployer']['type'] }}-{{ job_vars['__meta__']['deployer']['scm_ref'] }}"

- name: Callback - Job Launch status
  debug:
    msg: Placeholder, callback goes here

- name: Wait for job to complete
  tower_job_wait:
    job_id:   "{{ r_tower_job_launch.id }}"
    timeout:  "{{ tower_job_timeout | default(1800) }}"
  register: r_tower_job_status

- name: Callback - Job Status
  debug:
    msg: Placeholder, callback goes here
...
