---
- name: "Launch requested job of type {{ babylon_deployer_action }} of {{ babylon_scm_reference }}"
  tower_job_launch:
    job_template:     "{{ babylon_deployer_action }}-{{ babylon_deployer_type }}-{{ babylon_scm_reference }}"
    inventory:        "empty-inventory-{{ babylon_region | default (anarchy_region) | default('dev') }}"
    extra_vars:       "@{{ babylon_manifest_directory }}/{{ babylon_deployer_type }}-{{ babylon_deployer_action }}-{{ babylon_scm_reference }}-{{ guid }}.yml"
  register:       r_tower_job_launch

- when:
    - babylon_callback_url is defined
    - babylon_callback_token is defined
  name: Callback with Job Launch Status
  import_role:
    name: babylon-callback
    allow_duplicates: yes
  vars:
    babylon_callback_event: started
    babylon_message:
      - "{{ babylon_deployer_action }}-{{ babylon_deployer_type }}-{{ babylon_scm_reference }}"

- name: Callback - Job Launch status
  debug:
    msg: Placeholder, callback goes here

- name: Wait for job to complete
  tower_job_wait:
    job_id:   "{{ r_tower_job_launch.id }}"
    timeout:  "{{ tower_job_timeout | default(1800) }}"
  register: r_tower_job_status

- name: Callback - Job Status
  debug:
    msg: Placeholder, callback goes here
...
