---
- name: Create empty inventories for each instance group
  tower_inventory:
    name:                       "{{ tower_inventory_name }}-{{ instance_group }}"
    description:                "{{ tower_inventory_description }}"
    organization:               "{{ tower_orgainzation }}"
    state:                      "{{ tower_inventory_state }}"
  loop: "{{ tower_instance_groups }}"
  loop_control:
    loop_var: instance_group
...
