---
- name: Create tower organization
  tower_organization:
    name:               "{{ account_id }}"
    description:        "{{ account_id }} account"
    state:              "{{ acount_state | default('present') }}"
...
