---
- name: Create tower organization
  tower_organization:
    name:               "{{ job_vars['__meta__']['tower']['organization'] }}"
    description:        "{{ job_vars['__meta__']['tower']['organization'] }} Account"
    state:              "{{ tower_organization_state | default('present') }}"
    validate_certs:     no
...
