---
- name: "Create Tower Job Template for {{ job_vars['__meta__']['deployer']['type'] }} {{ job_vars['__meta__']['tower']['action'] }}"
  tower_job_template:
    name: >-                     
                                  {{ 
                                    job_vars['__meta__']['tower']['action'] ~ '-' 
                                    ~ job_vars['__meta__']['deployer']['type'] ~ '-'
                                    ~ job_vars['__meta__']['deployer']['scm_ref'] 
                                  }}
    job_type:                     run
    inventory:                    "{{ tower_inventory_name | default('empty-inventory-default') }}"
    project: >-
                                  {{ 
                                    job_vars['__meta__']['deployer']['type'] ~ '-'
                                    ~ job_vars['__meta__']['deployer']['scm_ref']
                                  }}
    playbook:                     "{{ job_vars['__meta__']['deployer']['entry_point'] }}"
    state:                        present
    credential:                   "{{ tower_job_credential | default('') }}"
    concurrent_jobs_enabled:      yes
    extra_vars_path: >-
                                  {{ 
                                    babylon_manifest_directory ~ '/'
                                    ~ job_vars['__meta__']['deployer']['type'] ~ '-'
                                    ~ job_vars['__meta__']['tower']['action'] ~ '-'
                                    ~ job_vars['__meta__']['deployer']['scm_ref'] ~ '-'
                                    ~ job_vars['guid'] ~ '.yml' 
                                  }}
...
