---
- name: Output values of Contracted Interface variables
  debug:
    msg:
      - "deployment_id:           {{ deployment_id          | default('UNDEFINED') }}"
      - "deployer_type:           {{ deployer_type          | default('UNDEFINED') }}"
      - "cloud_provider:          {{ cloud_provider         | default('UNDEFINED') }}"
      - "cloud_region:            {{ cloud_region           | default('UNDEFINED') }}"
      - "account_id:              {{ account_id             | default('UNDEFINED') }}"
      - "requester_id:            {{ requester_id           | default('UNDEFINED') }}"
      - "babylon_callback_url:    {{ babylon_callback_url   | default('UNDEFINED') }}"
      - "babylon_callback_token:  {{ babylon_callback_token | default('UNDEFINED') }}"
      - "environment_type:        {{ environment_type       | default('UNDEFINED') }}"
      - "environment_level:       {{ environment_level      | default('UNDEFINED') }}"
      - "environment_parameters:  {{ environment_parameters | default('UNDEFINED') }}"

- when: babylon_callback_url is defined
  name: Callback to provided URL
  block:

    - name: Debug callback URL
      debug:
        msg:          "Callback defined: {{ babylon_callback_url }}"
        verbosity:    2

    - name: Callback to providec callback URL
      import_role:
        name: babylon-callback
      vars:
        babylon_callback_url:       "{{ babylon_callback_url }}"
        babylon_callback_token:     "{{ babylon_callback_token }}"
        babylon_callback_stage:     Initial
        babylon_callback_event:     SUCCESS
        babylon_callback_message:   Parameters recieved, getting ready to create
...
