---
- name: Create null inventory
  tower_inventory:
    name:                       "null-inventory-{{ item.name }}"
    description:                "{{ tower_inventory_description }}"
    organization:               "{{ tower_orgainzation }}"
    state:                      "{{ tower_inventory_state | default('present') }}"
  loop: "{{ tower_instance_groups }}"
...
