---
deployer_playbook_name: main.yml

deployer_action:        deploy

scm_tag:                ocp-clientvm-prod-1.4
scm_type:               git
scm_url:                https://github.com/redhat-cop/agnosticd.git
...
