---
- name: Include in memory tasks
  include_tasks: in_memory_inventory.yml

- name: Generate name for backup file
  set_fact:
    now: '{{ lookup("pipe", "date +%F-%T") }}'

- name: Current installed tower version
  uri:   
    url: https://tower1.babylontest.example.opentlc.com/api/v2/ping/
    url_password: "{{ tower_admin_password}}"
    url_username: "{{ tower_username}}"
    method: GET 
    return_content: True
    validate_certs: False
  register: installed_tower
        
- name: Print current version
  debug: var=installed_tower.json.version

- name: fail if retore tower version is different from installed 
  fail: 
    msg: "Version differs"
  when: installed_tower.json.version != tower_version.split('-')[0]

- name: Download tower setup for version {{ tower_version }}
  unarchive:
    src: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_version }}.tar.gz
    dest: "{{ setup_dir }}"
    remote_src: yes 
        
- name: Generate Inventory
  template:
    src: tower_template_inventory.j2
    dest:  "{{ setup_dir }}/ansible-tower-setup-{{ tower_version }}/inventory"  

- name: Run Backup script
#   shell: ./setup.sh -b -e "backup_dest={{ setup_dir }}/ansible-tower-setup-{{ tower_version}}/backup_store"
  shell: ./setup.sh -b 
  args:
    chdir: "{{ setup_dir }}/ansible-tower-setup-{{ tower_version }}"

- name: Copy inventory file into backup_store
  copy:
    src: "{{ setup_dir }}/ansible-tower-setup-{{ tower_version}}/inventory"
    dest: "{{ setup_dir }}/ansible-tower-setup-{{ tower_version}}/backup_store"
        
- name: Archiving backup
  archive:
    path: "{{ setup_dir }}/ansible-tower-setup-{{ tower_version }}/backup_store"
    dest: "{{ setup_dir }}/ansible-tower-setup-{{ tower_version }}/full_tower_backup-{{ tower_version }}-{{ now }}"
    format: gz

- name: upload backup file
  copy:
    src: "{{ setup_dir }}/ansible-tower-setup-{{ tower_version }}/full_tower_backup-{{ tower_version }}-{{ now }}"
    dest: /tmp
    notify: remove backup tar from setup directory 
        
