---
- name: Confirm all necessary Tower components exist and launch job
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Create tower project
      tower_project:
        tower_config_file:        ./tower_cli.cfg
        name:                     agnosticd-ocp-clientvm-prod-1.4
        description:              OCP Client VM 1.4
        organization:             GPTE
        state:                    present
        scm_type:                 git
        scm_url:                  https://github.com/redhat-cop/agnosticd.git
        scm_branch:               ocp-clientvm-prod-1.4

    - name: Create job template via a tower_cli.cfg file
      tower_job_template:
        tower_config_file:        ./tower_cli.cfg
        name:                     job-via-tower-cli-file
        playbook:                 ansible/main.yml
        project:                  agnosticd-ocp-clientvm-prod-1.4
        job_type:                 run
        inventory:                foo
        state:                    present

    - name: Create tower Ping job template
      tower_job_template:
        tower_host:               "t35"
        tower_username:           "admin"
        tower_password:
        name:                     "try1"
        playbook:                 "ansible/main.yml"
        project:                  "agnosticd-ocp-clientvm-prod-1.4"
        job_type:                 "run"
        inventory:                "null-inventory"

#    - name: Set playbook name fact dependant on action
#      set_fact:
#        playbook_name: "{{ deployer_playbook_name if ( deployer_action == 'deploy') else destroyer_playbook_name }}"
#    - name: Create tower project
#      tower_job_template:
#        tower_host:               "{{ tower_host }}"
#        tower_username:           "{{ tower_username }}"
#        tower_password:           "{{ tower_password }}"
#        name:                     "{{ deployer_action }}-{{ deployer_type }}-{{ scm_tag | default(scm_branch) }}"
#        job_type:                 "{{ job_type }}"
#        inventory:                "{{ tower_inventory_name }}"
#        project:                  "{{ deployer_type }}-{{ scm_tag | default(scm_branch) }}"
#        playbook:                 "{{ playbook_path }}/{{ playbook_name }}"
#        state:                    "{{ tower_job_template_state }}"
#        credential:               "{{ cloud_provider_machine_credential }}"
...
