---
- when: babylon_git_reference is not defined
  block:
    - name: Lookup latest git tag
      command: >-
        git ls-remote --tags --sort=v:refname 
        --refs https://github.com/redhat-cop/agnosticd.git 
        "{{ git_tag_prefix }}*" 
      register: r_git_tag_search  
      vars:
        git_tag_prefix: ocp4-workshop-prod

    - when: r_git_tag_search['rc'] == 0   
      block:
        - name: Output tag 
          set_fact:
            babylon_git_reference: "{{ r_git_tag_search['stdout_lines'][-1] | regex_replace('.*refs\/tags\/', '') }}"

        - name: Output tag 
          debug: 
            var: babylon_git_reference
            verbosity: 2
...
