---
- name: "Launch requested job of type {{ deployer_action }} of {{ scm_reference }}"
  tower_job_launch:
    job_template:     debug
    inventory:        empty-inventory-dev
    extra_vars:       "@/tmp/debug.yml"
  register: r_tower_job_launch


    #extra_vars:           "@{{ extra_var_file_directory }}/{{ deployer_type }}-{{ scm_reference }}-{{ guid }}.yml"
...
