---
- name: Respond to a babylon API endpoint contracted interface ping
  hosts: localhost
  gather_facts: false
  become: false

  roles:

    - role: 
        name: babylon-callback
      vars:
        babylon_callback_url:       http://my.callback.com/api/v2/callback
        babylon_callback_event:     FAILED
        babylon_callback_message:  "Project tag does not exist"
        babylon_callback_message1:  "Project1 tag does not exist"
...
