---
- name: Manage tower
  hosts: tower
  gather_facts: false
  vars:
    tower_packages:
    - ansible-tower-venv-tower
    - ansible-tower-venv-ansible
    - ansible-tower-server
    - ansible-tower
    - ansible-tower-ui
    tower_directories:
    - /var/lib/pgsql
    - /var/lib/awx
    - /var/lib/rabbitmq


  tasks:

  - name: Shutdown tower
    block:

    - name: Shutdown running tower
      command: ansible-tower-service stop
      register: r_tower_stop
      tags:
      - shutdown-tower

    - name: Output result of tower shutdown
      debug:
          var: r_tower_stop
          verbosity: 2

  - name: Remove tower packages
    yum:
      name: "{{ tower_packages }}"
      state: absent

  - name: Remove rabbitmq packages
    yum:
      name: rabbitmq-server
      state: absent

  - name: Remove Tower artifact directories
    file:
      state: absent
      path: "{{ item }}"
    loop: "{{ tower_directories }}"
...
