---

- hosts: localhost
  gather_facts: false
  roles:
    - babylon-git-agnosticV
    - babylon-inventory
   
     

- hosts: bastions
  become: true
  gather_facts: false
  pre_tasks:
    - include_vars: "/tmp/agnosticV/GPTE.yml"
  
  roles:
    - babylon-backup
