---

- hosts: localhost
  gather_facts: false
  roles:
    - babylon-git-agnosticV
    - babylon-inventory
  tasks:
    - command: pip freeze
      register: output 

    - debug: var=output
    - name: storing output of pip in custom_fact
      set_fact:
        pip_freeze: "{{ output.stdout_lines }}"
   
     

- hosts: bastions
  become: true
  gather_facts: false
  pre_tasks:
    - include_vars: "/tmp/agnosticV/gpte.yml"
  
  roles:
    - babylon-backup

