- hosts: localhost
  gather_facts: false
  tasks:
  - name: Vars from anarchy sample
    include_vars:
       file: ./sample_info.yml
  - name: Project Create for configs
    tower_project:
      name: "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}"
      description: testing
      organization: gpte
      state: present
      scm_update_on_launch: True
      scm_update_cache_timeout: 60
      scm_url: https://github.com/prakhar1985/agnosticd.git
      scm_branch: development
      scm_type: git
  
  - name: Deploy config Job
    tower_job_template:
      name: "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}-job" 
      job_type: run
      inventory: empty-inventory
      project: "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}"
      playbook: ansible/main.yml
      state: present
  - name: Update job template to add creds
    shell: tower-cli job_template associate_credential --job-template "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}-job" --credential prakhar_aws_credential 
  - name: update job template with extra vars
    shell: tower-cli job_template modify -n "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}-job" -e @./sample_info.yml -e @/tmp/agnosticV/{{account_id}}.yml 

