- hosts: localhost
  gather_facts: false
  tasks:
  - name: Vars from anarchy sample
    include_vars:
       file: ./sample_info.yml
  - name: Project Create for configs
    tower_project:
      name: "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}"
      description: testing
      organization: gpte
      state: present
      scm_update_on_launch: True
      scm_update_cache_timeout: 60
      scm_url: https://github.com/prakhar1985/agnosticd.git
      scm_branch: development
      scm_type: git
  
