---
- name: Ensure all tower components exist for an anarchy deployment
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:
    tower_host:         t35
    tower_username:         admin
    tower_password:     r3dh4t1!
    tower_config_file:  ./t35_tower_config_file
    scm_tag:            ocp-clientvm-prod-1.4
    scm_type:           git
    scm_url:            https://github.com/redhat-cop/agnosticd.git

  tasks:

    - name: Stub task - save meta info
      debug:
        msg: Save any __meta__ vars to file

    - name: Create tower project
      tower_project:
        name:                       test-proj-1
        description:                Automagically created project"
        organization:               GPTE
        state:                      present
        tower_username:             "{{ tower_username }}"
        tower_password:             "{{ tower_password }}"
        tower_host:                 "{{ tower_host }}"
        scm_type:                   "{{ scm_type }}"
        scm_url:                    "{{ scm_url }}"
        scm_branch:                 "{{ scm_tag }}"
        scm_update_on_launch:       True
        scm_update_cache_timeout:   60
