- hosts: localhost
  gather_facts: false
  tasks:
  - name: Vars from anarchy sample
    include_vars:
       file: ./sample_info.yml
  - name: Project Create for configs
    tower_project:
      name: "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}"
      description: testing
      organization: gpte
      state: present
      scm_update_on_launch: True
      scm_update_cache_timeout: 60
      scm_url: https://github.com/prakhar1985/agnosticd.git
      scm_branch: development
      scm_type: git
  - name: AgnosticV cloning job if not created
    tower_job_template: 
      name: AgnosticV Cloner
      job_type: run
      inventory: empty-inventory
      project: babylon-dev
      playbook: babylon-tower/ansible/agnosticv-cloner.yml
      state: present
  - name: Deploye config Job
    tower_job_template:
      name: Deploy config 
      job_type: run
      inventory: empty-inventory
      project: "{{env_type}}-{{aws_region}}-{{guid}}-{{email}}"
      playbook: ansible/main.yml
      state: present
#      extra_vars_path: "/tmp/agnosticV/{{account_id}}.yml"  


#guid: test01
#cloud_provider: ec2
#aws_region: ap-southeast-2
#deployer_type: agnosticd
#account_id: gpte
#email: psrivast@redhat.com
#env_type: ans-tower-prod
