---
- name: Create Tower Project without instance group
  tower_project:
    name: >-
                                {{ 
                                  job_vars['__meta__']['deployer']['type'] ~ '-'
                                  job_vars['__meta__']['deployer']['scm_ref'] 
                                }}
    description:                "{{ job_vars['__meta__']['tower']['organization'] }}"
    organization:               "{{ job_vars['__meta__']['tower']['organization'] }}"
    state:                      "{{ tower_project_state }}"
    scm_type:                   "{{ job_vars['__meta__']['deployer']['scm_type'] }}"
    scm_url:                    "{{ job_vars['__meta__']['deployer']['scm_url'] }}"
    scm_branch:                 "{{ job_vars['__meta__']['deployer']['scm_ref'] }}"
    scm_update_on_launch:       "{{ babylon_scm_update_on_launch | default('no') }}"
    scm_update_cache_timeout:   "{{ babylon_scm_update_cache_timeout }}"
  register: r_tower_project  
  
- when: r_tower_project.changed  
  name: Pause to allow project sync
  pause:
    seconds:                    "{{ project_sync_pause_seconds | default(20) }}"
...
