---
# Tower config

# Org config

tower_project_name:                 "{{ deployer_type }}-{{ scm_reference | default(scm_branch) }}"
tower_organization:                 "{{ account_id }}"
tower_project_state:                present

# SCM config

babylon_scm_update_on_launch:       yes
babylon_scm_update_cache_timeout:   0
babylon_scm_clean:                  yes
...
