---
# Tower config

# Org config

tower_project_name:         "{{ deployer_type }}-{{ scm_tag | default(scm_branch) }}"
tower_orgainzation:         "{{ account_id }}"
tower_project_state:        present

# SCM config

scm_type:                   git
scm_url:                    https://github.com/redhat-cop/agnosticd.git
scm_tag:                    development
scm_branch:                 development
scm_update_on_launch:       yes
scm_update_cache_timeout:   0
scm_clean:                  yes
...
